//UNIVERSIDADE DO VALE DO ITAJAÍ - UNIVALI
//Escola do Mar, Ciência e Tecnologia
//Curso de Ciência da Computação – Campus Kobrasol
//Disciplina: Compiladores
//Professor:  Alessandro Mueller
//Alunos:     Guilherme Veiga, Bruno Frassetto e Fabio Volkmann Coelho

package semantico;


import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class TableObject extends javax.swing.JFrame {

    private List<Instruction> instructions = new ArrayList<>();
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblObject;

    /**
     * Creates new form TO
     */
    public TableObject() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableObject().setVisible(true);
            }
        });
    }

    public void setInstructions(List<Instruction> inst) {
        this.instructions = inst;
    }

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tblObject.getModel();
        while (tblObject.getModel().getRowCount() > 0)
            model.removeRow(0);
        for (Instruction instruction : instructions) {
            switch (instruction.getParameter().getType()) {
                case TipoDeDado.TYPE_INT:
                    model.addRow(new Object[]
                            {
                                    instruction.getPointer(), instruction.getCode(), instruction.getParameter().getObj()
                            });
                    break;
                case TipoDeDado.TYPE_REAL:
                    model.addRow(new Object[]
                            {
                                    instruction.getPointer(), instruction.getCode(), instruction.getParameter().getObj()
                            });
                    break;
                case TipoDeDado.TYPE_STRING:
                    model.addRow(new Object[]
                            {
                                    instruction.getPointer(), instruction.getCode(), instruction.getParameter().getObj()
                            });
                    break;
                case TipoDeDado.TYPE_BOOLEAN:
                    model.addRow(new Object[]
                            {
                                    instruction.getPointer(), instruction.getCode(), (float) instruction.getParameter().getObj()
                            });
                    break;
                default:
                    System.out.println(instruction.getPointer());
                    System.out.println(instruction.getParameter().getType());
                    System.out.println(instruction.getCode());
                    System.out.println("Erro na TableObject tipo indefinido no comando" + instruction.getCode() + "!");
                    break;
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblObject = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Código Objeto");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tblObject.setModel(new DefaultTableModel(
                new Object[][]
                        {

                        },
                new String[]
                        {
                                "Ponteiro", "Instrução", "Parâmetro"
                        }
        ));
        jScrollPane1.setViewportView(tblObject);

        getContentPane().add(jScrollPane1);

        setBounds(0, 0, 409, 343);
    }// </editor-fold>//GEN-END:initComponents

    static class TipoDeDado {

        public static final int TYPE_INT = 1;
        public static final int TYPE_REAL = 2;
        public static final int TYPE_STRING = 3;
        public static final int TYPE_BOOLEAN = 4;
    }
    // End of variables declaration                   
}
